blask-5/app/models/blog.py
from app import db
from flask.ext.mongoengine.wtf import model_form


class BlogPost(db.Document):
    author = db.StringField(required=True, max_length=100)
    title = db.StringField(required=True, max_length=100)
    body = db.StringField(required=True)

BlogPostForm = model_form(BlogPost)

blask-5/app/__init__.py
from flask import Flask
from flask.ext.mongoengine import MongoEngine

app = Flask(__name__)

app.config['DEBUG'] = True
app.config['MONGODB_SETTINGS'] = {'db': 'blask'}
app.config['SECRET_KEY'] = 'another random string'

db = MongoEngine(app)

# Import and register the Blueprints
from app.routes.blog import blog
from app.routes.home import home
app.register_blueprint(blog)
app.register_blueprint(home)

blask-5/app/routes/blog.py
from flask import Blueprint, render_template, redirect, url_for, request
from app.models.blog import BlogPost, BlogPostForm

# Create the blog Blueprint.  Note that all routes on the blog blueprint have
# '/blog' prepended to them.
blog = Blueprint('blog', __name__, url_prefix='/blog')


@blog.route('/')  # Accessible at /blog/
def blog_page():
    """The blog page."""
    posts = BlogPost.objects()
    return render_template('blog.html', posts=posts)


@blog.route('/new', methods=['GET', 'POST'])
def new():
    """Create a new post"""
    form = BlogPostForm(request.form)

    if request.method == 'POST' and form.validate():
        form.save()
        return redirect(url_for('blog.blog_page'))

    return render_template('new.html', form=form)

blask-5/app/routes/home.py
from flask import Blueprint, render_template

home = Blueprint('home', __name__)


@home.route('/')
def home_page():
    """The home page."""
    return render_template('home.html')

blask-5/app/templates/blog.html
{% extends "home.html" %}
{% block title %}Blog | {{ super() }}{% endblock %}
{% block current_page %}Blog{% endblock %}

{% block content %}
<h2>Check out my posts!</h2>

<ul class="posts">
{% for post in posts %}
	<li class="post">
		<h3>{{ post.title }} <small>by {{ post.author }}</small></h3>
		<p>{{ post.body }}</p>
	</li>
{% endfor %}
</ul>
{% endblock %}

blask-5/app/templates/home.html
<html>
<head>
  <title>{% block title %}Blask!{% endblock %}</title>
  <link rel='stylesheet'
      type='text/css'
      href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700,300,400'>
  <link rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
  <nav>
    <div class="content">
      <h1><a href="/">Blask!</a></h1>
      <h2>{% block current_page %}Home{% endblock %}</h2>
      <ul class="menu">
        <li>
          <a href="{{ url_for('home.home_page') }}">Home</a>
        </li>
        <li>
          <a href="{{ url_for('blog.blog_page') }}">Blog</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="content">
    {% block content %}
    <h2>Welcome to Blask!</h2>
    {% endblock %}
  </div>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>
</html>

blask-5/app/templates/new.html
{% extends "home.html" %}
{% block title %}Blog | {{ super() }}{% endblock %}
{% block current_page %}Blog{% endblock %}

{% block content %}
<h2>Create a New Post</h2>

<form action="" method="POST">
	{{ form.csrf_token }}
	<div>
		{{ form.title.label}}
		{{ form.title }}
	</div>
	<div>
		{{ form.author.label }}
		{{ form.author }}
	</div>
	<div>
		{{ form.body.label }}
		{{ form.body }}
	</div>
	<input type="submit" value="Create">
</form>
{% endblock %}